language: php

env:
  - NETTE=2.1.*
  - NETTE=2.2.*
  - NETTE=2.3.*
  - NETTE=@dev

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

before_script:
  - "php tests/prepare-composer.php"
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .

script: bash ./tests/run-tests.sh

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
